export const theme = {
    colors: {
        primary: '#2E7D52',
        primaryLight: '#E8F5EE',
        primaryDark: '#1B5E35',
        background: '#F5F7F5',
        card: '#FFFFFF',
        border: '#E8E8E8',
        textDark: '#1A1A2E',
        textBody: '#4A4A4A',
        textSubtle: '#888888',
        textLight: '#BBBBBB',
        danger: '#E63946',
        dangerLight: '#FFF0F0',
        warning: '#FF8C00',
        warningLight: '#FFF3E0',
        info: '#1565C0',
        infoLight: '#E3F2FD',
        purple: '#6A1B9A',
        purpleLight: '#F3E5F5',
        white: '#FFFFFF',
        black: '#000000',
    },
    typography: {
        screenTitle: { fontSize: 24, fontWeight: '700' as const },
        sectionHeading: { fontSize: 18, fontWeight: '700' as const },
        cardTitle: { fontSize: 16, fontWeight: '600' as const },
        body: { fontSize: 15, fontWeight: '400' as const },
        label: { fontSize: 13, fontWeight: '500' as const },
        caption: { fontSize: 12, fontWeight: '400' as const },
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 32,
        xxl: 48,
    },
    radius: {
        sm: 8,
        md: 12,
        lg: 16,
        xl: 20,
        full: 999,
    },
    shadow: {
        small: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.08,
            shadowRadius: 4,
            elevation: 2,
        },
        medium: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.12,
            shadowRadius: 8,
            elevation: 4,
        },
    },
} as const;